version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: carshop
      POSTGRES_PASSWORD: carshop
      POSTGRES_DB: carshop
    ports:
      - "5432:5432"
