version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env


  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: carshop
      POSTGRES_PASSWORD: carshop
      POSTGRES_DB: carshop
    ports:
      - "5432:5432"
